SudokuWeb/SudokuWeb/SudokuSolver/urls.py
from django.conf.urls import url
from . import views

app_name = "SudokuSolver"

urlpatterns = [
    url(r'^signup/$', views.signup, name="signup"),
    url(r'^login/$', views.sudoku_login, name="login"),
    url(r'^logout/$', views.logout, name="logout"),
    url (r'^home$', views.home, name='home'),
    url (r'^load$', views.load, name='load'),
    url (r'^save$', views.save, name='save'),
    url (r'^delete$', views.delete, name='delete'),
    url (r'^test$', views.test1, name='test'),
    url (r'^test2$', views.test2, name='test2'),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
]

SudokuWeb/SudokuWeb/SudokuWeb/urls.py
"""
Definition of urls for SudokuWeb.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views
from django.urls import include, path
from django.contrib import admin

import SudokuSolver.forms
import SudokuSolver.views

# Uncomment the next lines to enable the admin:
# from django.conf.urls import include
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^$', SudokuSolver.views.home, name='home'),
    url(r'^about$', SudokuSolver.views.about, name='about'),
    #url(r'^home', include ('SudokuSolver.urls')),
    url(r'^Sudoku/', include ('SudokuSolver.urls')),
    #url (r'^test$', SudokuSolver.views.test1, name='test'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
]

SudokuWeb/SudokuWeb/SudokuSolver/views.py
"""
Definition of views.
"""

from django.http import HttpRequest
from django.http import HttpResponse
from django.template import RequestContext
from datetime import datetime
from . import forms
from django.shortcuts import render, redirect, HttpResponseRedirect
import SudokuSolver.code.SudokuEnginePy as se
import SudokuSolver.code.Globals as Globals
from SudokuSolver.models import saveGrid, getUserList, getGridList, retrieveGridHeader, retrieveGridCells, checkConn, getUserName, deleteGridHeader
import random
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
import cx_Oracle
from django.urls import reverse

# Sign up new users
def signup (request):
    if request.method == 'POST':
         form = UserCreationForm (request.POST)
         if form.is_valid ():
             user = form.save ()
             #  log the user in
             login (request, user)
             return redirect ('SudokuSolver:home')
    else:
        form = UserCreationForm()
    return render(request, 'Signup.html', { 'form': form })

# Login
def sudoku_login (request):
    request.session ['message'] = ""
    if request.method == 'POST':
        form = AuthenticationForm (data=request.POST)

        if form.is_valid():
            # Log the user in
            user = form.get_user ()

            retval = checkConn ()
            if retval != 0:
                request.session ['message'] = "Oracle database connection problem!"
                request.session.modified = True
                return redirect ('SudokuSolver:home')

            csr = Globals.db.cursor ()
            sqlrowcnt = csr.var (cx_Oracle.NUMBER)
            retval  = csr.var (cx_Oracle.NUMBER)
            params = csr.callproc ('PCK_SUDOKU_SOLVER.insertUser', (user.username, sqlrowcnt, retval)) # Returns all IN and OUT params in params as a list (or tuple)

            if params[2] == -1: # User already exists, do nothing
                pass
            elif params[2] != 0:
                Globals.oraError = str (params[2])
                request.session ['message'] = "Database error: " + Globals.oraError
                return redirect ('SudokuSolver:home')
            
            login (request, user)
            Globals.user = user.username
            if 'next' in request.POST:
                return redirect (request.POST.get('next'))
            else:
                return redirect ('SudokuSolver:home')
    else:
        form = AuthenticationForm ()
    return render (request, 'Login.html', { 'form': form })

# About page (todo)
def about (request):
    """Renders the about page."""
    assert isinstance(request, HttpRequest)
    return render(request,  'SudokuSolver/about.html', {'title':'About', 'message':'Your application description page.', 'year':datetime.now().year,})

# Home page
def home (request):
    Globals.user = request.user.username

    # ********** POST Solve **********
    if request.method == 'POST' and 'solveit' in request.POST:
        request.session ['message'] = ""
        form = forms.GridForm (request.POST)
        if form.is_valid(): # If gridlist is empty, the form is not valid. This field is required!
            inputGrid = [0,]
            for i in range (1, 82, 1):
                if ('scell%02d' % i) in form.cleaned_data:
                    if form.cleaned_data ['scell%02d' % i] != "":
                        inputGrid.append (int (form.cleaned_data ['scell%02d' % i]))
                    else:
                        inputGrid.append (0)
            form.data = form.data.copy () # It is non-mutable so needs copying first
            if se.SuDoKuEngine (inputGrid) == 0:
                for i in range (1, 82, 1):
                    form.data ['tcell%02d' % i] = Globals.gridArea [i]
                    if form.cleaned_data ['scell%02d' % i] != "":
                        form.fields ['tcell%02d' % i].widget.attrs ['class']='c b x'
            else:
                for i in range (1, 82, 1):
                    if inputGrid [i] != 0:
                        form.fields ['tcell%02d' % i].widget.attrs ['class']='c b x'
                request.session ['message'] = "The grid is invalid!"
            request.session ['home_grid_data'] = inputGrid # Add form data to session
            request.session ['home_created_datetime'] = datetime.now ().strftime ("%Y-%m-%d %H:%M:%S")
            request.session ['home_time_taken'] = "%f" % ((int (Globals.timeEnd - Globals.timeStart)) / 1000000000)
            form.data['time_taken'] = request.session ['home_time_taken']
            form.data['created_datetime'] = request.session ['home_created_datetime'] 
            #sess_age = request.session.get_expiry_age () # Get the expiry
            #sess_exp = request.session.get_expire_at_browser_close ()
            form.data['log_window']=Globals.log
    # Reset grids
    elif request.method == 'POST' and 'resetit' in request.POST: # The reset button was clicked
        request.session ['message'] = ""
        form = forms.GridForm (request.POST)
        form.data = form.data.copy () # The data is not mutable, has to be copied
        for i in range (1, 82, 1):
            form.data ['scell%02d' % i] = ""
        for i in range (1, 82, 1):
            form.data ['tcell%02d' % i] = ""
        form.data ['log_window']=""
    # Hun lang
    elif request.method == 'POST' and 'langhun' in request.POST: # The Hungarian flag was clicked
        request.session ['message'] = ""
        form = forms.GridForm (request.POST)
        form.data = form.data.copy () # It is non-mutable so needs copying first
        Globals.langCode = 1
        if len (Globals.gridArea) != 0:
            for i in range (1, 82, 1):
                form.data ['tcell%02d' % i] = Globals.gridArea [i]
                if form.data ['scell%02d' % i] != "":
                    form.fields ['tcell%02d' % i].widget.attrs ['class']='c b x'
        form.fields ['title'].widget.attrs ['placeholder'] = "Egy már előzőleg megoldott rács elnevezése"
        form.fields ['comment'].widget.attrs ['placeholder'] = "A Sudoku rács alkotójának megjegyzései"                                                                                            
        form.fields ['log_window'].widget.attrs ['placeholder'] = "********************* SuDoKu megoldó napló ******************\n**** Applikáció ami próbálgatást és visszalépést használ ****\n*** Technológia Python 3.7, Django 2.1 és cx_Oracle 6.4.1 ***\n"
    # Eng lang
    elif request.method == 'POST' and 'langeng' in request.POST: # The Hungarian flag was clicked
        request.session ['message'] = ""
        form = forms.GridForm (request.POST)
        form.data = form.data.copy () # It is non-mutable so needs copying first
        Globals.langCode = 0
        if len (Globals.gridArea) != 0:
            for i in range (1, 82, 1):
                form.data ['tcell%02d' % i] = Globals.gridArea [i]
                if form.data ['scell%02d' % i] != "":
                    form.fields ['tcell%02d' % i].widget.attrs ['class']='c b x'
        form.fields ['title'].widget.attrs ['placeholder'] = "The title of a previously saved grid"
        form.fields ['comment'].widget.attrs ['placeholder'] = "Sudoku grid creator's comment"
        form.fields ['log_window'].widget.attrs ['placeholder'] = "********************** SuDoKu Solver log ********************\n****** Application using brute force and backtracking *******\n*** Powered by Python 3.7, Django 2.1 and cx_Oracle 6.4.1 ***\n"
    # Logout
    elif request.method == 'POST' and 'logout' in request.POST:
        request.session ['message'] = ""
        form = forms.GridForm (request.POST)

        form.fields['title'].initial = request.session ['home_title']
        form.fields['created_datetime'].initial = request.session ['home_created_datetime']
        form.fields['time_taken'].initial = request.session ['home_time_taken']
        form.fields['comment'].initial = request.session ['home_comment']
        grid = request.session['home_grid_data']

        if len (grid) != 0:
            for i in range (1, 82, 1):
                if grid[i] != 0:
                    form.fields ['scell%02d' % i].initial=str (grid[i])
        if len (Globals.gridArea) == 82 :
            for i in range (1, 82, 1):
                form.fields ['tcell%02d' % i].initial = Globals.gridArea [i]
                if form.fields ['scell%02d' % i].initial != None:
                    form.fields ['tcell%02d' % i].widget.attrs ['class']='c b x'

        # Save session variables as logout clears them
        temp_sess = {}
        temp_sess ['home_title'] = request.session ['home_title']
        temp_sess ['home_created_datetime'] = request.session ['home_created_datetime']
        temp_sess ['home_time_taken'] = request.session ['home_time_taken']
        temp_sess ['home_comment'] = request.session ['home_comment']
        temp_sess ['home_grid_data'] = request.session ['home_grid_data']
        
        logout (request)

        # Restore all session variables because logout flushes the session data
        request.session ['home_grid_data'] = temp_sess ['home_grid_data']
        request.session ['home_title'] = temp_sess ['home_title']
        request.session ['home_created_datetime'] = temp_sess ['home_created_datetime']
        request.session ['home_time_taken'] = temp_sess ['home_time_taken']
        request.session ['home_comment'] = temp_sess ['home_comment']
        if Globals.langCode == 0:
            request.session ['message'] = "User " + Globals.user + " logged out"
        else:
            request.session ['message'] = "Felhasználó " + Globals.user + " kijelentkezve"
        Globals.user = ""
        
    elif request.method == 'POST' and 'login' in request.POST:
        return redirect ('SudokuSolver:login')

    # ********** GET **********
    else:
        form = forms.GridForm ()

SudokuWeb/SudokuWeb/SudokuSolver/templates/SudokuSolver/DeleteGrid.html
{% load static from staticfiles %}
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8" />

        <!-- <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
        <meta http-equiv="Pragma" content="no-cache" />
        <meta http-equiv="Expires" content="0" /> -->

        <title>{% if language == 0 %} Sudoku solver {% else %} Sudoku megoldó {% endif %}</title>
        <link rel="stylesheet" href="{% static 'style.css' %}">

        <script>
            function myAlert (msg, okay){
                document.getElementById("opaque").style.opacity = "0.5";
                var elem = document.createElement('div');
                elem.style.cssText = 'position: absolute; top:0; left:0; width: 100%;height:100%;z-index:100;opacity:0.4;';
                elem.id = 'over';
                document.body.appendChild(elem);

                document.body.innerHTML += '<div id="myAlertPrnt"> <div id="myAlert"> <table id="myAlert_table"> <tr id="myAlert_tr"> <td id="myAlert_td"><p id="myAlert_content"></p></td> </tr> <tr id="myAlert_tr"> <td id="myAlert_td"><button id="myAlert_ok" onclick="myAlertOked ()"></button></td> </tr> </table> </div> </div>'

                document.getElementById('myAlert_content').innerHTML = msg;
                document.getElementById ('myAlert_ok').innerHTML = okay;
                document.body.style.cursor = "wait";
            }

            function myAlertOked(){
                var parent = document.getElementById ('myAlertPrnt') ;
                var child = document.getElementById ('myAlert') ;
                parent.removeChild (child) ;
                document.body.style.cursor = "default";
                var element = document.getElementById('over');
                var parent2 = document.getElementById ('body') ;
                parent2.removeChild(element);
                document.getElementById("opaque").style.opacity = "1";
            }
        </script>

    </head>
    <body id="body">
        <div id="opaque">
        <div style="float:left; width:30%;">.</div>
        <div style="float:left; margin-left:-120px">
            <div style="float:left; margin-top:10px; margin-left:800px; color:white"> Welcome {{user.username}}, Session start: {{ user.last_login}}</div>
            <h2 style="color:white;position:relative; left:260px;">{% if language == 0 %} Delete the grid {% else %} A rács törlése {% endif %}</h2>
            <a style="position:relative; left:20px; top:10px" href="{% url 'SudokuSolver:home' %}"><img src="{% static 'SudokuLogo.png' %}" alt="Sudoku Solver" width="130"></a>
            <div style="position:relative; top: 0px">
                <ul style="float:left; margin-left:230px; position:relative; top:-40px;">
                    <li style="float:left;"><a style=" height:15px; vertical-align:central; align-content:center" href="{% url 'SudokuSolver:home' %}">{% if language == 0 %} Home {% else %} Kezdőlap {% endif %}</a></li>
                    <li style="float:left;"><a style=" height:15px; vertical-align:central; align-content:center"href="#about">{% if language == 0 %} About {% else %} Rólam {% endif %}</a></li>
                    <li style="float:left;"><a style=" height:15px; vertical-align:central; align-content:center"href="{% url 'SudokuSolver:test' %}">{% if language == 0 %} Test {% else %} Teszt {% endif %}</a></li>
                </ul>
            </div>
            <form method="post" novalidate>
                {% csrf_token %}
                <input type="hidden" name="submit_param" value="">
                
                <div class="field" style="width:295px; clear:both; position:relative; top:40px; left:20px"><b>{% if language == 0 %} Select a user from the list {% else %} Válassz egy felhasználót {% endif %}</b></div>
                <div style="width:295px; position:relative; top:40px; left:20px">{{ form.userlist }}</div>
                
                <div class="field" style="width:295px; clear:both; position:relative; top:80px; left:20px"><b>{% if language == 0 %} Select a user's grid from the list {% else %} Válassz egy felhasznnálói rácsot {% endif %}</b></div>
                <div style="width:295px; position:relative; top:80px; left:20px">{{ form.gridlist }}</div>

                    <div class="field" style="position:relative; top:-40px; left:322px; width:137px; text-align:center"><b>{% if language == 0 %} Grid info {% else %} Rács infó {% endif %}</b></div>
                    <table border="1" border-style="solid" style="position:relative; top:-41px; left: 320px">
                        <tr>
                            <th class="label">{% if language == 0 %} Title {% else %} Megnevezés {% endif %}</th>
                            <td class="field">
                                {% if form.title.errors %}
                                    <ul style="background-color:white; color:red">
                                        {% for error in form.title.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                                {{ form.title }}
                                {% if form.title.help_text %}
                                    <br />{{ form.title.help_text }}
                                {% endif %}
                            </td>
                        </tr>

                        <tr>
                            <th class="label">{% if language == 0 %} Created date time {% else %} Létrehozás ideje {% endif %}</th>
                            <td class="field">
                                {% if form.created_datetime.errors %}
                                    <ul style="background-color:white; color:red">
                                        {% for error in form.created_datetime.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                                {{ form.created_datetime }}
                                {% if form.created_datetime.help_text %}
                                    <br />{{ form.created_datetime.help_text }}
                                {% endif %}
                            </td>
                        </tr>
                        <tr>
                            <th class="label">{% if language == 0 %} Time taken to solve {% else %} Megoldás időtartama {% endif %}</th>
                            <td class="field">
                                {% if form.time_taken.errors %}
                                    <ul style="background-color:white; color:red">
                                        {% for error in form.time_taken.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                                {{ form.time_taken }} {% if language == 0 %} seconds {% else %} másodperc {% endif %}
                                {% if form.time_taken.help_text %}
                                    <br />{{ form.time_taken.help_text }}
                                {% endif %}
                            </td>
                        </tr>
                   
                        <tr>
                            <th class="label">{% if language == 0 %} Comment {% else %} Megjegyzés {% endif %}</th>
                            <td class="field">
                                {% if form.comment.errors %}
                                    <ul style="background-color:white; color:red">
                                        {% for error in form.comment.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                                {{ form.comment }}
                                {% if form.comment.help_text %}
                                    <br />{{ form.comment.help_text }}
                                {% endif %}
                            </td>
                        </tr>
                    </table>

                <div style="clear:left; position:relative; left:210px; top:20px">
                    <div class="field"; style="position:relative; top:-40px; left:3px; width:100px; text-align:center"><b>{% if language == 0 %} Saved grid {% else %} Elmentett rács {% endif %}</b></div>
                    <table class="wh" cellspacing="1" style="position:relative; top:-36px;">
                        {% for field in form.visible_fields %}
                            {% if field.field.widget.attrs.celltype == 's' %}
                                {% if field.auto_id == "id_scell01" or field.auto_id == "id_scell10" or field.auto_id == "id_scell19" or field.auto_id == "id_scell28" or field.auto_id == "id_scell37" or field.auto_id == "id_scell46" or field.auto_id == "id_scell55" or field.auto_id == "id_scell64" or field.auto_id == "id_scell73" %}
                                    <tr>
                                {% endif %}
                                <td>
                                    {{ field }}
                                </td>
                                {% if field.auto_id == "id_scell09" or field.auto_id == "id_scell18" or field.auto_id == "id_scell27" or field.auto_id == "id_scell36" or field.auto_id == "id_scell45" or field.auto_id == "id_scell54" or field.auto_id == "id_scell63" or field.auto_id == "id_scell72" or field.auto_id == "id_scell81" %}
                                    </tr>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    </table>
                </div>
                <div style="float:left"><button type="submit" name="deleteit" style="position:relative; top:-230px; left:550px; height:45px; width: 70px; font-weight: bold; background-color: #ffcc99;">{% if language == 0 %} Delete {% else %} Töröl {% endif %}</button></div>
            </form>
        </div>
        <div id="footer" style="position:relative; clear:both; top:50px">
            <hr>
            <footer style="text-align:center; color:antiquewhite">
                  Sudoku Solver - Powered by Python, Django and Oracle
            </footer>
        </div>
        {% if request.session.message != "" %}
            <script>
                myAlert('{{ request.session.message }}', "OK") ;
            </script>
        {% endif %}
        </div>
    </body>
</html>

SudokuWeb/SudokuWeb/SudokuSolver/templates/SudokuSolver/HomePage.html
{% extends 'base_layout.html' %}
{% load static from staticfiles %}

{% block content %}

<form method="post" novalidate>
    {% csrf_token %}

    <div style="float:left;">
        <a style="position:relative; left:0px; top:-105px" href="{% url 'SudokuSolver:home' %}"><img src="{% static 'SudokuLogo.png' %}" alt="Sudoku Solver" width="130"></a>
        <div class="field"; style="position:relative; top:-73px; left:3px; width:100px; text-align:center"><b>{% if language == 0 %} Starting grid {% else %} Kiinduló rács {% endif %}</b></div>
        <button type="submit" name="resetit" style="position:relative; top:-104px; left:130px; height:30px; font-weight: bold; background-color: #ffcc99;">{% if language == 0 %} Reset {% else %} Töröl {% endif %}</button>
        <table class="wh" cellspacing="1" style="position:relative; top:-100px;">
            {% for field in form.visible_fields %}
                {% if field.field.widget.attrs.celltype == 's' %}
                    {% if field.auto_id == "id_scell01" or field.auto_id == "id_scell10" or field.auto_id == "id_scell19" or field.auto_id == "id_scell28" or field.auto_id == "id_scell37" or field.auto_id == "id_scell46" or field.auto_id == "id_scell55" or field.auto_id == "id_scell64" or field.auto_id == "id_scell73" %}
                        <tr>
                    {% endif %}
                    <td>
                        {{ field }}
                    </td>
                    {% if field.auto_id == "id_scell09" or field.auto_id == "id_scell18" or field.auto_id == "id_scell27" or field.auto_id == "id_scell36" or field.auto_id == "id_scell45" or field.auto_id == "id_scell54" or field.auto_id == "id_scell63" or field.auto_id == "id_scell72" or field.auto_id == "id_scell81" %}
                        </tr>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </table>
        <div class="field"; style="position:relative; top:-72px; left:3px; width:90px; text-align:center"><b>{% if language == 0 %} Solved grid {% else %} Megoldás {% endif %}</b></div>
        <button type="submit" name="solveit" style="position:relative; top:-105px; left:130px; height:30px; font-weight: bold; background-color: #ffcc99;" onclick="solving()">{% if language == 0 %} Solve {% else %} Megold {% endif %}</button>
        <button type="submit" name="langhun" style="background-image: url(/static/HunFlag.gif); background-repeat: no-repeat; background-size: cover; width: 40px; height: 25px; position: relative; top: -540px; left: 710px;"></button>
        <button type="submit" name="langeng" style="background-image: url(/static/BriFlag.gif); background-repeat: no-repeat; background-size: cover; width: 40px; height: 25px; position: relative; top: -540px; left: 730px;"></button>
        {% if user.username != "" %}
            <button type="submit" name="logout" style="width: 100px; height: 25px; position: relative; top: -550px; left: 800px; background-color: #ffcc99;"">{% if language == 0 %} Logout {% else %} Kijelentkezés {% endif %}</button>
        {% else %}
            <button type="submit" name="login" style="width: 100px; height: 25px; position: relative; top: -550px; left: 800px; background-color: #ffcc99;"">{% if language == 0 %} Login {% else %} Bejelentkezés {% endif %}</button>
        {% endif %}
        <table style="position:relative; top:-105px" class="wh" cellspacing="1">
            {% for field in form.visible_fields %}
                {% if field.field.widget.attrs.celltype == 't' %}
                    {% if field.auto_id == "id_tcell01" or field.auto_id == "id_tcell10" or field.auto_id == "id_tcell19" or field.auto_id == "id_tcell28" or field.auto_id == "id_tcell37" or field.auto_id == "id_tcell46" or field.auto_id == "id_tcell55" or field.auto_id == "id_tcell64" or field.auto_id == "id_tcell73" %}
                        <tr>
                    {% endif %}
                    <td>
                        {{ field }}
                    </td>
                    {% if field.auto_id == "id_tcell09" or field.auto_id == "id_tcell18" or field.auto_id == "id_tcell27" or field.auto_id == "id_tcell36" or field.auto_id == "id_tcell45" or field.auto_id == "id_tcell54" or field.auto_id == "id_tcell63" or field.auto_id == "id_tcell72" or field.auto_id == "id_tcell81" %}
                        </tr>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </table>
    </div>

    <div style="float:left; margin-left:60px">
        {% if form.non_field_errors %}
            <ul>
                {% for error in form.non_field_errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <div class="field" style="position:relative; top:-25px; left:2px; width:140px; text-align:center"><b>{% if language == 0 %} Saved grid info {% else %} Lementett rács infó {% endif %}
            </b></div>

        <table border="1" border-style="solid" style="position:relative; top:-23px">
            <tr>
                <th class="label">{% if language == 0 %} Title {% else %} Megnevezés {% endif %}</th>
                <td class="field">
                    {% if form.title.errors %}
                        <ul>
                            {% for error in form.title.errors %}
                                <li>{{ error }}</li>
                                {% endfor %}
                        </ul>
                    {% endif %}
                    {{ form.title }}
                    {% if form.title.help_text %}
                        <br />{{ form.title.help_text }}
                    {% endif %}
                </td>
            </tr>

            <tr>
                <th class="label">{% if language == 0 %} Created date time {% else %} Létrehozás ideje {% endif %}</th>
                <td class="field">
                    {% if form.created_datetime.errors %}
                        <ul>
                            {% for error in form.created_datetime.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    {{ form.created_datetime }}
                    {% if form.created_datetime.help_text %}
                         <br />{{ form.created_datetime.help_text }}
                    {% endif %}
                </td>
            </tr>
    
            <tr>
                <th class="label">{% if language == 0 %} Time taken to solve {% else %} Megoldás időtartama {% endif %}</th>
                <td class="field">
                    {% if form.time_taken.errors %}
                        <ul>
                            {% for error in form.time_taken.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    {{ form.time_taken }} {% if language == 0 %} seconds {% else %} másodperc {% endif %}
                    {% if form.time_taken.help_text %}
                        <br />{{ form.time_taken.help_text }}
                    {% endif %}
                </td>
            </tr>
    
            <tr>
                <th class="label">{% if language == 0 %} Comment {% else %} Megjegyzés {% endif %}</th>
                <td class="field">
                    {% if form.comment.errors %}
                        <ul>
                            {% for error in form.comment.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                       </ul>
                    {% endif %}
                    {{ form.comment }}
                    {% if form.comment.help_text %}
                        <br />{{ form.comment.help_text }}
                    {% endif %}
                </td>
            </tr>
        </table>

        <div style="position:relative; top: 12px">
            <div class="field"; style="position:relative; top:-21px; left:2px; width:140px; text-align:center"><b>{% if language == 0 %} Solver log {% else %} Megoldó napló {% endif %}</b></div>
            <div style="position:relative; top:-19px">
                {% if form.log_window.errors %}
                    <ul>
                        {% for error in form.log_window.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                {{ form.log_window }}
                {% if form.log_window.help_text %}
                    <br />{{ form.log_window.help_text }}
                {% endif %}
            </div>
        </div>
    </div>
</form>

{% endblock %}